### ISSUE TITLE
Header problem in rTree.cpp

### ISSUE THREAD

**Issue by StomyPX** [hackcraft-de/linwarrior#8]
I deleted the two lines containing `logstream << (*(&val));` in source/de/hackcraft/log/LevelStreamLogger.h as referenced by #6, but I still had a huge list of errors. On my system the headers included in source/de/hackcraft/world/sub/model/rTree.cpp run into some sort of namespacing problem and lose track of std::basic_string, leading to this error:
```
In file included from /usr/include/c++/10.2.0/iosfwd:39,
                 from /usr/include/c++/10.2.0/ios:38,
                 from /usr/include/c++/10.2.0/ostream:38,
                 from source/de/hackcraft/psi3d/GLS.h:20,
                 from source/de/hackcraft/world/sub/model/rTree.h:16,
                 from source/de/hackcraft/world/sub/model/rTree.cpp:1:
/usr/include/c++/10.2.0/bits/stringfwd.h:79:11: error: ‘basic_string’ does not name a type
   79 |   typedef basic_string<char>    string;
...
(Followed by a hundred other errors that this missing typedef causes)
```

I fixed it by moving
```
#include <string>
using std::string;
```
in rTree.cpp to the top of the file, before `#include "rTree.h"`. It's a hack but I can compile and play now so I've gotten what I wanted. In case it makes a difference I'm using Linux 5.10.36-2-MANJARO 64-bit, compiling with GCC 10.2.0.

**Comment by hackcraft-de** [comment]
As pointed out by user DMJC replacing (*(&val)) with (int*(&val)) should work.

**Comment by hackcraft-de** [comment]
As pointed out by user DMJC replacing `(*(&val))` with `(int*(&val))` should work.

**Comment by hackcraft-de** [comment]
Ok, finally fixed the issue compiling with more recent compilers.

Sorry for the long delay to you and the others who reported a variant of this issue rooted in the same compiler issue.

The compiler needed one of the loggin methods with another explicit parameter type because a type cast that did before wasn't working anymore. Plus a couple of other issues with changed standard libraries and inclusion problems.

Thank you for reporting the issue and hope this fixes the issue for you, don't resitate to report back if it does/n't work. :)
